name: Run DevOps Emulation

on:
  push:
    branches: [main]

jobs:
  emulate:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Python Emulation Script
        run: |
          cd scripts
          python3 run_emulation.py
