name: Cappucino Vibe Check

on:
  push:
    branches: [main]

jobs:
  vibecheck:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Cappucino's Vibe Check
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install requests
          python scripts/vibe_check.py


