name: Run DevOps Emulation

on:
  push:
    branches: [main]

jobs:
  emulate:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Python Emulation Script with Dependencies
        run: |
          cd scripts
          python3 -m venv venv
          source venv/bin/activate
          pip install requests
          python run_emulation.py
